#A play writen to deploy apache
- name: configure apache on amazon linux instances
  hosts: amazonclients
  tasks:
    - name: Upgrade all packages #yum update -y 
      yum:
        name: '*'
        state: latest
    - name: Install the latest version of Apache # install apache httpd
      yum:
        name: httpd
        state: latest
    - name: Start service httpd, if not started #systemctl start httpd
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Enable service httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
    - name: copy index file from controller to remote client
      ansible.builtin.copy:
        src: /home/ubuntu/index.html # on the controller 
        dest: /var/www/html/  # client